import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import AuthProvider from "@/context/AuthProvides";
import { Toaster } from "@/components/ui/toaster"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={inter.className}
        >
          {children}
          <Toaster/>
        </body>
      </AuthProvider>
    </html>
  );
}
